### ISSUE TITLE
hass-kumo Will No Longer Load after 0.2.0 Update via HACS

### ISSUE THREAD

**Issue by barndawgie** [dlarrick/hass-kumo#35]
Hi,
My integration was working fine until I ran the 0.2.0 release update via HACS. Now, it fails to load (the Home Assistant comes up).

Home assistnat log indicates the following:

```
Log Details (ERROR)
Logger: homeassistant.setup
Source: custom_components/kumo/__init__.py:131
First occurred: 9:38:07 PM (1 occurrences)
Last logged: 9:38:07 PM

Error during setup of component kumo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 190, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/kumo/__init__.py", line 131, in async_setup
    hass.data[KUMO_DATA] = KumoData(account, config[DOMAIN])
TypeError: __init__() missing 1 required positional argument: 'domain_options'
```

After forcing a downgrade to 0.1.6 via HACS, everything is working fine again.

**Comment by dlarrick** [comment]
Yes, that was my experience as well. Re-add the component via Configuration -> Integrations page and all is well. You will want to remove the old lines from configuration.yaml also.
