### ISSUE TITLE
error in log

### ISSUE THREAD

**Issue by galak** [dlarrick/hass-kumo#70]
Seeing this in my ha.log

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kumo/climate.py", line 107, in async_setup_entry
    data = hass.data[DOMAIN]
KeyError: 'kumo'
```

Not sure what might be going on here.

**Comment by dlarrick** [comment]
You'll probably get a better response on the HA forum thread as noted in this repo's README.

**Comment by dlarrick** [comment]
Closing some old tickets. Feel free to re-open with more info if this still occurs.
